/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AvaliacoesRouteImport } from './routes/avaliacoes'
import { Route as AgendarRouteImport } from './routes/agendar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as DashboardServicosRouteImport } from './routes/dashboard.servicos'
import { Route as DashboardProfissionaisRouteImport } from './routes/dashboard.profissionais'
import { Route as DashboardPerfilRouteImport } from './routes/dashboard.perfil'
import { Route as DashboardPagamentosRouteImport } from './routes/dashboard.pagamentos'
import { Route as DashboardMensagensRouteImport } from './routes/dashboard.mensagens'
import { Route as DashboardEnderecosRouteImport } from './routes/dashboard.enderecos'
import { Route as DashboardAvaliacoesRouteImport } from './routes/dashboard.avaliacoes'
import { Route as DashboardAjudaRouteImport } from './routes/dashboard.ajuda'
import { Route as DashboardAgendamentosRouteImport } from './routes/dashboard.agendamentos'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AdminServicosRouteImport } from './routes/admin.servicos'
import { Route as AdminRelatoriosRouteImport } from './routes/admin.relatorios'
import { Route as AdminProfissionaisRouteImport } from './routes/admin.profissionais'
import { Route as AdminPagamentosRouteImport } from './routes/admin.pagamentos'
import { Route as AdminNotificacoesRouteImport } from './routes/admin.notificacoes'
import { Route as AdminMensagensRouteImport } from './routes/admin.mensagens'
import { Route as AdminLogsRouteImport } from './routes/admin.logs'
import { Route as AdminCuponsRouteImport } from './routes/admin.cupons'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'
import { Route as AdminClientesOnlineRouteImport } from './routes/admin.clientes-online'
import { Route as AdminClientesRouteImport } from './routes/admin.clientes'
import { Route as AdminCategoriasRouteImport } from './routes/admin.categorias'
import { Route as AdminAvaliacoesRouteImport } from './routes/admin.avaliacoes'
import { Route as AdminAgendamentosRouteImport } from './routes/admin.agendamentos'

const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AvaliacoesRoute = AvaliacoesRouteImport.update({
  id: '/avaliacoes',
  path: '/avaliacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendarRoute = AgendarRouteImport.update({
  id: '/agendar',
  path: '/agendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardServicosRoute = DashboardServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfissionaisRoute = DashboardProfissionaisRouteImport.update({
  id: '/profissionais',
  path: '/profissionais',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPerfilRoute = DashboardPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPagamentosRoute = DashboardPagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMensagensRoute = DashboardMensagensRouteImport.update({
  id: '/mensagens',
  path: '/mensagens',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEnderecosRoute = DashboardEnderecosRouteImport.update({
  id: '/enderecos',
  path: '/enderecos',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAvaliacoesRoute = DashboardAvaliacoesRouteImport.update({
  id: '/avaliacoes',
  path: '/avaliacoes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAjudaRoute = DashboardAjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAgendamentosRoute = DashboardAgendamentosRouteImport.update({
  id: '/agendamentos',
  path: '/agendamentos',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/admin/usuarios',
  path: '/admin/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminServicosRoute = AdminServicosRouteImport.update({
  id: '/admin/servicos',
  path: '/admin/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRelatoriosRoute = AdminRelatoriosRouteImport.update({
  id: '/admin/relatorios',
  path: '/admin/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProfissionaisRoute = AdminProfissionaisRouteImport.update({
  id: '/admin/profissionais',
  path: '/admin/profissionais',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPagamentosRoute = AdminPagamentosRouteImport.update({
  id: '/admin/pagamentos',
  path: '/admin/pagamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNotificacoesRoute = AdminNotificacoesRouteImport.update({
  id: '/admin/notificacoes',
  path: '/admin/notificacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMensagensRoute = AdminMensagensRouteImport.update({
  id: '/admin/mensagens',
  path: '/admin/mensagens',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/admin/logs',
  path: '/admin/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCuponsRoute = AdminCuponsRouteImport.update({
  id: '/admin/cupons',
  path: '/admin/cupons',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/admin/configuracoes',
  path: '/admin/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClientesOnlineRoute = AdminClientesOnlineRouteImport.update({
  id: '/admin/clientes-online',
  path: '/admin/clientes-online',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClientesRoute = AdminClientesRouteImport.update({
  id: '/admin/clientes',
  path: '/admin/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriasRoute = AdminCategoriasRouteImport.update({
  id: '/admin/categorias',
  path: '/admin/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAvaliacoesRoute = AdminAvaliacoesRouteImport.update({
  id: '/admin/avaliacoes',
  path: '/admin/avaliacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAgendamentosRoute = AdminAgendamentosRouteImport.update({
  id: '/admin/agendamentos',
  path: '/admin/agendamentos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agendar': typeof AgendarRoute
  '/avaliacoes': typeof AvaliacoesRoute
  '/cadastro': typeof CadastroRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contato': typeof ContatoRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/servicos': typeof ServicosRoute
  '/admin/agendamentos': typeof AdminAgendamentosRoute
  '/admin/avaliacoes': typeof AdminAvaliacoesRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/clientes-online': typeof AdminClientesOnlineRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/cupons': typeof AdminCuponsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/mensagens': typeof AdminMensagensRoute
  '/admin/notificacoes': typeof AdminNotificacoesRoute
  '/admin/pagamentos': typeof AdminPagamentosRoute
  '/admin/profissionais': typeof AdminProfissionaisRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/servicos': typeof AdminServicosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/dashboard/agendamentos': typeof DashboardAgendamentosRoute
  '/dashboard/ajuda': typeof DashboardAjudaRoute
  '/dashboard/avaliacoes': typeof DashboardAvaliacoesRoute
  '/dashboard/enderecos': typeof DashboardEnderecosRoute
  '/dashboard/mensagens': typeof DashboardMensagensRoute
  '/dashboard/pagamentos': typeof DashboardPagamentosRoute
  '/dashboard/perfil': typeof DashboardPerfilRoute
  '/dashboard/profissionais': typeof DashboardProfissionaisRoute
  '/dashboard/servicos': typeof DashboardServicosRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agendar': typeof AgendarRoute
  '/avaliacoes': typeof AvaliacoesRoute
  '/cadastro': typeof CadastroRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contato': typeof ContatoRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/servicos': typeof ServicosRoute
  '/admin/agendamentos': typeof AdminAgendamentosRoute
  '/admin/avaliacoes': typeof AdminAvaliacoesRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/clientes-online': typeof AdminClientesOnlineRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/cupons': typeof AdminCuponsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/mensagens': typeof AdminMensagensRoute
  '/admin/notificacoes': typeof AdminNotificacoesRoute
  '/admin/pagamentos': typeof AdminPagamentosRoute
  '/admin/profissionais': typeof AdminProfissionaisRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/servicos': typeof AdminServicosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/dashboard/agendamentos': typeof DashboardAgendamentosRoute
  '/dashboard/ajuda': typeof DashboardAjudaRoute
  '/dashboard/avaliacoes': typeof DashboardAvaliacoesRoute
  '/dashboard/enderecos': typeof DashboardEnderecosRoute
  '/dashboard/mensagens': typeof DashboardMensagensRoute
  '/dashboard/pagamentos': typeof DashboardPagamentosRoute
  '/dashboard/perfil': typeof DashboardPerfilRoute
  '/dashboard/profissionais': typeof DashboardProfissionaisRoute
  '/dashboard/servicos': typeof DashboardServicosRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agendar': typeof AgendarRoute
  '/avaliacoes': typeof AvaliacoesRoute
  '/cadastro': typeof CadastroRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contato': typeof ContatoRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/servicos': typeof ServicosRoute
  '/admin/agendamentos': typeof AdminAgendamentosRoute
  '/admin/avaliacoes': typeof AdminAvaliacoesRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/clientes-online': typeof AdminClientesOnlineRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/cupons': typeof AdminCuponsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/mensagens': typeof AdminMensagensRoute
  '/admin/notificacoes': typeof AdminNotificacoesRoute
  '/admin/pagamentos': typeof AdminPagamentosRoute
  '/admin/profissionais': typeof AdminProfissionaisRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/servicos': typeof AdminServicosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/dashboard/agendamentos': typeof DashboardAgendamentosRoute
  '/dashboard/ajuda': typeof DashboardAjudaRoute
  '/dashboard/avaliacoes': typeof DashboardAvaliacoesRoute
  '/dashboard/enderecos': typeof DashboardEnderecosRoute
  '/dashboard/mensagens': typeof DashboardMensagensRoute
  '/dashboard/pagamentos': typeof DashboardPagamentosRoute
  '/dashboard/perfil': typeof DashboardPerfilRoute
  '/dashboard/profissionais': typeof DashboardProfissionaisRoute
  '/dashboard/servicos': typeof DashboardServicosRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agendar'
    | '/avaliacoes'
    | '/cadastro'
    | '/como-funciona'
    | '/contato'
    | '/dashboard'
    | '/login'
    | '/reset-password'
    | '/servicos'
    | '/admin/agendamentos'
    | '/admin/avaliacoes'
    | '/admin/categorias'
    | '/admin/clientes'
    | '/admin/clientes-online'
    | '/admin/configuracoes'
    | '/admin/cupons'
    | '/admin/logs'
    | '/admin/mensagens'
    | '/admin/notificacoes'
    | '/admin/pagamentos'
    | '/admin/profissionais'
    | '/admin/relatorios'
    | '/admin/servicos'
    | '/admin/usuarios'
    | '/dashboard/agendamentos'
    | '/dashboard/ajuda'
    | '/dashboard/avaliacoes'
    | '/dashboard/enderecos'
    | '/dashboard/mensagens'
    | '/dashboard/pagamentos'
    | '/dashboard/perfil'
    | '/dashboard/profissionais'
    | '/dashboard/servicos'
    | '/admin/'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agendar'
    | '/avaliacoes'
    | '/cadastro'
    | '/como-funciona'
    | '/contato'
    | '/login'
    | '/reset-password'
    | '/servicos'
    | '/admin/agendamentos'
    | '/admin/avaliacoes'
    | '/admin/categorias'
    | '/admin/clientes'
    | '/admin/clientes-online'
    | '/admin/configuracoes'
    | '/admin/cupons'
    | '/admin/logs'
    | '/admin/mensagens'
    | '/admin/notificacoes'
    | '/admin/pagamentos'
    | '/admin/profissionais'
    | '/admin/relatorios'
    | '/admin/servicos'
    | '/admin/usuarios'
    | '/dashboard/agendamentos'
    | '/dashboard/ajuda'
    | '/dashboard/avaliacoes'
    | '/dashboard/enderecos'
    | '/dashboard/mensagens'
    | '/dashboard/pagamentos'
    | '/dashboard/perfil'
    | '/dashboard/profissionais'
    | '/dashboard/servicos'
    | '/admin'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/agendar'
    | '/avaliacoes'
    | '/cadastro'
    | '/como-funciona'
    | '/contato'
    | '/dashboard'
    | '/login'
    | '/reset-password'
    | '/servicos'
    | '/admin/agendamentos'
    | '/admin/avaliacoes'
    | '/admin/categorias'
    | '/admin/clientes'
    | '/admin/clientes-online'
    | '/admin/configuracoes'
    | '/admin/cupons'
    | '/admin/logs'
    | '/admin/mensagens'
    | '/admin/notificacoes'
    | '/admin/pagamentos'
    | '/admin/profissionais'
    | '/admin/relatorios'
    | '/admin/servicos'
    | '/admin/usuarios'
    | '/dashboard/agendamentos'
    | '/dashboard/ajuda'
    | '/dashboard/avaliacoes'
    | '/dashboard/enderecos'
    | '/dashboard/mensagens'
    | '/dashboard/pagamentos'
    | '/dashboard/perfil'
    | '/dashboard/profissionais'
    | '/dashboard/servicos'
    | '/admin/'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendarRoute: typeof AgendarRoute
  AvaliacoesRoute: typeof AvaliacoesRoute
  CadastroRoute: typeof CadastroRoute
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  ContatoRoute: typeof ContatoRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ServicosRoute: typeof ServicosRoute
  AdminAgendamentosRoute: typeof AdminAgendamentosRoute
  AdminAvaliacoesRoute: typeof AdminAvaliacoesRoute
  AdminCategoriasRoute: typeof AdminCategoriasRoute
  AdminClientesRoute: typeof AdminClientesRoute
  AdminClientesOnlineRoute: typeof AdminClientesOnlineRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminCuponsRoute: typeof AdminCuponsRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminMensagensRoute: typeof AdminMensagensRoute
  AdminNotificacoesRoute: typeof AdminNotificacoesRoute
  AdminPagamentosRoute: typeof AdminPagamentosRoute
  AdminProfissionaisRoute: typeof AdminProfissionaisRoute
  AdminRelatoriosRoute: typeof AdminRelatoriosRoute
  AdminServicosRoute: typeof AdminServicosRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avaliacoes': {
      id: '/avaliacoes'
      path: '/avaliacoes'
      fullPath: '/avaliacoes'
      preLoaderRoute: typeof AvaliacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendar': {
      id: '/agendar'
      path: '/agendar'
      fullPath: '/agendar'
      preLoaderRoute: typeof AgendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/servicos': {
      id: '/dashboard/servicos'
      path: '/servicos'
      fullPath: '/dashboard/servicos'
      preLoaderRoute: typeof DashboardServicosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profissionais': {
      id: '/dashboard/profissionais'
      path: '/profissionais'
      fullPath: '/dashboard/profissionais'
      preLoaderRoute: typeof DashboardProfissionaisRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/perfil': {
      id: '/dashboard/perfil'
      path: '/perfil'
      fullPath: '/dashboard/perfil'
      preLoaderRoute: typeof DashboardPerfilRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pagamentos': {
      id: '/dashboard/pagamentos'
      path: '/pagamentos'
      fullPath: '/dashboard/pagamentos'
      preLoaderRoute: typeof DashboardPagamentosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/mensagens': {
      id: '/dashboard/mensagens'
      path: '/mensagens'
      fullPath: '/dashboard/mensagens'
      preLoaderRoute: typeof DashboardMensagensRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/enderecos': {
      id: '/dashboard/enderecos'
      path: '/enderecos'
      fullPath: '/dashboard/enderecos'
      preLoaderRoute: typeof DashboardEnderecosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/avaliacoes': {
      id: '/dashboard/avaliacoes'
      path: '/avaliacoes'
      fullPath: '/dashboard/avaliacoes'
      preLoaderRoute: typeof DashboardAvaliacoesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ajuda': {
      id: '/dashboard/ajuda'
      path: '/ajuda'
      fullPath: '/dashboard/ajuda'
      preLoaderRoute: typeof DashboardAjudaRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/agendamentos': {
      id: '/dashboard/agendamentos'
      path: '/agendamentos'
      fullPath: '/dashboard/agendamentos'
      preLoaderRoute: typeof DashboardAgendamentosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/servicos': {
      id: '/admin/servicos'
      path: '/admin/servicos'
      fullPath: '/admin/servicos'
      preLoaderRoute: typeof AdminServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/relatorios': {
      id: '/admin/relatorios'
      path: '/admin/relatorios'
      fullPath: '/admin/relatorios'
      preLoaderRoute: typeof AdminRelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/profissionais': {
      id: '/admin/profissionais'
      path: '/admin/profissionais'
      fullPath: '/admin/profissionais'
      preLoaderRoute: typeof AdminProfissionaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pagamentos': {
      id: '/admin/pagamentos'
      path: '/admin/pagamentos'
      fullPath: '/admin/pagamentos'
      preLoaderRoute: typeof AdminPagamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/notificacoes': {
      id: '/admin/notificacoes'
      path: '/admin/notificacoes'
      fullPath: '/admin/notificacoes'
      preLoaderRoute: typeof AdminNotificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/mensagens': {
      id: '/admin/mensagens'
      path: '/admin/mensagens'
      fullPath: '/admin/mensagens'
      preLoaderRoute: typeof AdminMensagensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/admin/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cupons': {
      id: '/admin/cupons'
      path: '/admin/cupons'
      fullPath: '/admin/cupons'
      preLoaderRoute: typeof AdminCuponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/admin/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/clientes-online': {
      id: '/admin/clientes-online'
      path: '/admin/clientes-online'
      fullPath: '/admin/clientes-online'
      preLoaderRoute: typeof AdminClientesOnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/clientes': {
      id: '/admin/clientes'
      path: '/admin/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AdminClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categorias': {
      id: '/admin/categorias'
      path: '/admin/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AdminCategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/avaliacoes': {
      id: '/admin/avaliacoes'
      path: '/admin/avaliacoes'
      fullPath: '/admin/avaliacoes'
      preLoaderRoute: typeof AdminAvaliacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/agendamentos': {
      id: '/admin/agendamentos'
      path: '/admin/agendamentos'
      fullPath: '/admin/agendamentos'
      preLoaderRoute: typeof AdminAgendamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardAgendamentosRoute: typeof DashboardAgendamentosRoute
  DashboardAjudaRoute: typeof DashboardAjudaRoute
  DashboardAvaliacoesRoute: typeof DashboardAvaliacoesRoute
  DashboardEnderecosRoute: typeof DashboardEnderecosRoute
  DashboardMensagensRoute: typeof DashboardMensagensRoute
  DashboardPagamentosRoute: typeof DashboardPagamentosRoute
  DashboardPerfilRoute: typeof DashboardPerfilRoute
  DashboardProfissionaisRoute: typeof DashboardProfissionaisRoute
  DashboardServicosRoute: typeof DashboardServicosRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAgendamentosRoute: DashboardAgendamentosRoute,
  DashboardAjudaRoute: DashboardAjudaRoute,
  DashboardAvaliacoesRoute: DashboardAvaliacoesRoute,
  DashboardEnderecosRoute: DashboardEnderecosRoute,
  DashboardMensagensRoute: DashboardMensagensRoute,
  DashboardPagamentosRoute: DashboardPagamentosRoute,
  DashboardPerfilRoute: DashboardPerfilRoute,
  DashboardProfissionaisRoute: DashboardProfissionaisRoute,
  DashboardServicosRoute: DashboardServicosRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendarRoute: AgendarRoute,
  AvaliacoesRoute: AvaliacoesRoute,
  CadastroRoute: CadastroRoute,
  ComoFuncionaRoute: ComoFuncionaRoute,
  ContatoRoute: ContatoRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ServicosRoute: ServicosRoute,
  AdminAgendamentosRoute: AdminAgendamentosRoute,
  AdminAvaliacoesRoute: AdminAvaliacoesRoute,
  AdminCategoriasRoute: AdminCategoriasRoute,
  AdminClientesRoute: AdminClientesRoute,
  AdminClientesOnlineRoute: AdminClientesOnlineRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminCuponsRoute: AdminCuponsRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminMensagensRoute: AdminMensagensRoute,
  AdminNotificacoesRoute: AdminNotificacoesRoute,
  AdminPagamentosRoute: AdminPagamentosRoute,
  AdminProfissionaisRoute: AdminProfissionaisRoute,
  AdminRelatoriosRoute: AdminRelatoriosRoute,
  AdminServicosRoute: AdminServicosRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
