/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as ProfissionaisRouteImport } from './routes/profissionais'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AvaliacoesRouteImport } from './routes/avaliacoes'
import { Route as AgendarRouteImport } from './routes/agendar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardServicosRouteImport } from './routes/dashboard.servicos'
import { Route as DashboardPerfilRouteImport } from './routes/dashboard.perfil'
import { Route as DashboardPagamentosRouteImport } from './routes/dashboard.pagamentos'
import { Route as DashboardAjudaRouteImport } from './routes/dashboard.ajuda'
import { Route as DashboardAgendamentosRouteImport } from './routes/dashboard.agendamentos'

const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfissionaisRoute = ProfissionaisRouteImport.update({
  id: '/profissionais',
  path: '/profissionais',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AvaliacoesRoute = AvaliacoesRouteImport.update({
  id: '/avaliacoes',
  path: '/avaliacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendarRoute = AgendarRouteImport.update({
  id: '/agendar',
  path: '/agendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardServicosRoute = DashboardServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPerfilRoute = DashboardPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPagamentosRoute = DashboardPagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAjudaRoute = DashboardAjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAgendamentosRoute = DashboardAgendamentosRouteImport.update({
  id: '/agendamentos',
  path: '/agendamentos',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agendar': typeof AgendarRoute
  '/avaliacoes': typeof AvaliacoesRoute
  '/cadastro': typeof CadastroRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contato': typeof ContatoRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/profissionais': typeof ProfissionaisRoute
  '/servicos': typeof ServicosRoute
  '/dashboard/agendamentos': typeof DashboardAgendamentosRoute
  '/dashboard/ajuda': typeof DashboardAjudaRoute
  '/dashboard/pagamentos': typeof DashboardPagamentosRoute
  '/dashboard/perfil': typeof DashboardPerfilRoute
  '/dashboard/servicos': typeof DashboardServicosRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agendar': typeof AgendarRoute
  '/avaliacoes': typeof AvaliacoesRoute
  '/cadastro': typeof CadastroRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contato': typeof ContatoRoute
  '/login': typeof LoginRoute
  '/profissionais': typeof ProfissionaisRoute
  '/servicos': typeof ServicosRoute
  '/dashboard/agendamentos': typeof DashboardAgendamentosRoute
  '/dashboard/ajuda': typeof DashboardAjudaRoute
  '/dashboard/pagamentos': typeof DashboardPagamentosRoute
  '/dashboard/perfil': typeof DashboardPerfilRoute
  '/dashboard/servicos': typeof DashboardServicosRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agendar': typeof AgendarRoute
  '/avaliacoes': typeof AvaliacoesRoute
  '/cadastro': typeof CadastroRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contato': typeof ContatoRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/profissionais': typeof ProfissionaisRoute
  '/servicos': typeof ServicosRoute
  '/dashboard/agendamentos': typeof DashboardAgendamentosRoute
  '/dashboard/ajuda': typeof DashboardAjudaRoute
  '/dashboard/pagamentos': typeof DashboardPagamentosRoute
  '/dashboard/perfil': typeof DashboardPerfilRoute
  '/dashboard/servicos': typeof DashboardServicosRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agendar'
    | '/avaliacoes'
    | '/cadastro'
    | '/como-funciona'
    | '/contato'
    | '/dashboard'
    | '/login'
    | '/profissionais'
    | '/servicos'
    | '/dashboard/agendamentos'
    | '/dashboard/ajuda'
    | '/dashboard/pagamentos'
    | '/dashboard/perfil'
    | '/dashboard/servicos'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agendar'
    | '/avaliacoes'
    | '/cadastro'
    | '/como-funciona'
    | '/contato'
    | '/login'
    | '/profissionais'
    | '/servicos'
    | '/dashboard/agendamentos'
    | '/dashboard/ajuda'
    | '/dashboard/pagamentos'
    | '/dashboard/perfil'
    | '/dashboard/servicos'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/agendar'
    | '/avaliacoes'
    | '/cadastro'
    | '/como-funciona'
    | '/contato'
    | '/dashboard'
    | '/login'
    | '/profissionais'
    | '/servicos'
    | '/dashboard/agendamentos'
    | '/dashboard/ajuda'
    | '/dashboard/pagamentos'
    | '/dashboard/perfil'
    | '/dashboard/servicos'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendarRoute: typeof AgendarRoute
  AvaliacoesRoute: typeof AvaliacoesRoute
  CadastroRoute: typeof CadastroRoute
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  ContatoRoute: typeof ContatoRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  ProfissionaisRoute: typeof ProfissionaisRoute
  ServicosRoute: typeof ServicosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profissionais': {
      id: '/profissionais'
      path: '/profissionais'
      fullPath: '/profissionais'
      preLoaderRoute: typeof ProfissionaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avaliacoes': {
      id: '/avaliacoes'
      path: '/avaliacoes'
      fullPath: '/avaliacoes'
      preLoaderRoute: typeof AvaliacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendar': {
      id: '/agendar'
      path: '/agendar'
      fullPath: '/agendar'
      preLoaderRoute: typeof AgendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/servicos': {
      id: '/dashboard/servicos'
      path: '/servicos'
      fullPath: '/dashboard/servicos'
      preLoaderRoute: typeof DashboardServicosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/perfil': {
      id: '/dashboard/perfil'
      path: '/perfil'
      fullPath: '/dashboard/perfil'
      preLoaderRoute: typeof DashboardPerfilRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pagamentos': {
      id: '/dashboard/pagamentos'
      path: '/pagamentos'
      fullPath: '/dashboard/pagamentos'
      preLoaderRoute: typeof DashboardPagamentosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ajuda': {
      id: '/dashboard/ajuda'
      path: '/ajuda'
      fullPath: '/dashboard/ajuda'
      preLoaderRoute: typeof DashboardAjudaRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/agendamentos': {
      id: '/dashboard/agendamentos'
      path: '/agendamentos'
      fullPath: '/dashboard/agendamentos'
      preLoaderRoute: typeof DashboardAgendamentosRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAgendamentosRoute: typeof DashboardAgendamentosRoute
  DashboardAjudaRoute: typeof DashboardAjudaRoute
  DashboardPagamentosRoute: typeof DashboardPagamentosRoute
  DashboardPerfilRoute: typeof DashboardPerfilRoute
  DashboardServicosRoute: typeof DashboardServicosRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAgendamentosRoute: DashboardAgendamentosRoute,
  DashboardAjudaRoute: DashboardAjudaRoute,
  DashboardPagamentosRoute: DashboardPagamentosRoute,
  DashboardPerfilRoute: DashboardPerfilRoute,
  DashboardServicosRoute: DashboardServicosRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendarRoute: AgendarRoute,
  AvaliacoesRoute: AvaliacoesRoute,
  CadastroRoute: CadastroRoute,
  ComoFuncionaRoute: ComoFuncionaRoute,
  ContatoRoute: ContatoRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  ProfissionaisRoute: ProfissionaisRoute,
  ServicosRoute: ServicosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
